JWT_PUBLIC_KEY: 'JWT_PUBLIC_KEY'
JWT_SECRET_KEY: 'JWT_SECRET_KEY'
JWT_ALGORITHM: "HS256"
ACCESS_MINUTES: 15
REFRESH_DAYS: 14
VERIFY_MINUTES: 10
RESENDING_MINUTES: 1

DB_ALCHEMY: 'postgresql+psycopg://user:password@localhost/db_name'
DB_ALCHEMY_TEST: 'postgresql+psycopg://user:password@localhost/db_name_test'

EMAIL_HOST: 'smtp.EMAIL_HOST.ru'
EMAIL_PORT: 465
EMAIL_USERNAME: 'EMAIL_USERNAME@EMAIL_USERNAME.ru'
EMAIL_PASSWORD: 'EMAIL_PASSWORD'
EMAIL_FROM: 'EMAIL_FROM@EMAIL_FROM.ru'

CURRENCY_API_KEY: 'CURRENCY_API_KEY'
CURRENCY_API_ADDRESS: 'https://api.apilayer.com/currency_data'

DEFAULT_USERNAME: 'admin'
DEFAULT_PASSWORD: 'adminadmin'
DEFAULT_EMAIL: 'super_admin@example.com'